#! /usr/bin/env node
const program = require("commander");
const packageJson = require('../package.json');

program
  .version(packageJson.version, "-v --version")
  .command('branch')
  .description("simple-git 批量删除 git 分支：可视化、手动多选、模糊匹配精准选择")
  // 操作类型
  .option("-d, --delete [delete]", "删除分支操作(默认)")
  .option("-D, --delete-force [delete-force]", "强制删除分支操作")
  // 范围配置
  .option("-a, --all [all]", "所有分支")
  .option("-l, --local [local]", "仅本地分支(默认)")
  .option("-r, --remote [remote]", "仅远程分支")
  .option("-f, --fuzzy [fuzzy]", "模糊匹配")
  // 选择规则
  .option("-m, --multiple [multiple]", "是否为多选(默认为多选)")
  .option("-s, --selected [selected]", "是否选中(默认为多选)")
  // 其他
  .option("-y, --yes [yes]", "是否选中(默认为多选)")
  .option("-c, --cwd [cwd]", "项目地址(默认为当前目录)")

  .action((option) => {
    var option = Object.assign(
      {
        delete: true,
        deleteForce: false,
        all: false,
        local: true,
        remote: false,
        multiple: true,
        selected: false,
        yes: false,
        fuzzy: ''
      },
      option
    );
    // console.log(option);
    require('./lib/branch')(option)
  });

program.parse(process.argv);
